version: "3"

services:
  static-webpage:
    build:
      dockerfile: Dockerfile

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /c/Users/Admin/cmsc389T-web-template
      o: bind
