version: "3"

services:
  static-webpage:
    build:
      dockerfile: Dockerfile
    image: node-web-app
    container_name: website
    volumes:
      - node-app-volume:/home/node/app
    restart: unless-stopped
    ports:
      - "80:8080"

volumes:
  node-app-volume:
    driver: local
    driver_opts:
      type: none
      device: /c/Users/Admin/cmsc389T-web-template
      o: bind
